name: Test Workflow

on: [push]

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Hello World
        run: echo "Hello World"

      - name: List files
        run: ls -la
